"""Building project runtime images on the managed server.

An environment is a base image plus whatever the user wants installed on top.
Moonphase layers its own requirements over that base and builds the result on
the server itself, so defining a new environment needs no registry, no CI, and
no pre-publishing step — the definition is data, and the image is derived from
it on first use.

The generated Dockerfile is piped to `docker build -` over the existing SSH
connection, with no build context at all. Everything Moonphase needs is either
downloaded during the build or base64-encoded into the recipe, which is why
`tmux.conf` is inlined rather than COPYed.

Images are tagged with a hash of the recipe that produced them, so editing an
environment yields a different tag and existing projects keep running on the
image they were built with until they are restarted.
"""

from __future__ import annotations

import base64
import hashlib
import logging
import shlex

import asyncssh

from . import ssh
from .ssh import SSHError

log = logging.getLogger(__name__)

# Bump when the recipe below changes in a way that should rebuild every image.
# v4 added OpenCode and the Pydantic AI coder agent: an image built before it
# has neither binary, and a project set to one of those would launch nothing.
# v5 added the xclip shim: an image built before it has no bridge for the
# browser's clipboard, so pasting an image into the harness silently does
# nothing instead of attaching it.
RECIPE_VERSION = "6"

NODE_VERSION = "22.20.0"

# Packages Moonphase itself depends on inside a project container:
#   tmux     the session that outlives every client
#   socat    the preview tunnel's transport
#   iproute2 listening-port detection
#   git, curl, ca-certificates, openssh-client  the basics an agent needs
BASE_PACKAGES = [
    "ca-certificates", "curl", "git", "gnupg", "openssh-client", "less", "jq",
    "ripgrep", "fd-find", "tmux", "socat", "iproute2", "procps", "unzip",
    "xz-utils", "build-essential", "python3", "python3-pip", "python3-venv",
    "sudo", "tini", "locales",
]

TMUX_CONF = """# tmux configuration for Moonphase project containers.
set  -g  default-terminal "tmux-256color"
set  -ga terminal-overrides ",xterm-256color:Tc"
set  -g  history-limit 50000
set  -g  destroy-unattached off
set  -g  exit-empty off
set  -g  remain-on-exit off
setw -g  aggressive-resize on
set  -s  escape-time 0
set  -g  focus-events on
set  -g  mouse on
set  -g  base-index 1
setw -g  pane-base-index 1
set  -g  status-style "bg=#1a1b26,fg=#a9b1d6"
set  -g  status-left  " #[bold]moonphase#[default] "
set  -g  status-right " #{session_name} \\u00b7 %H:%M "
set  -g  status-left-length 30
"""

# Stands in for xclip so the harness's own clipboard-image paste works in a
# container with no X server and no real OS clipboard. Kept in sync by hand
# with infra/images/claude/xclip-shim.sh — see the comment there for how it
# fits together with sessions.stage_clipboard_image and Terminal.tsx.
XCLIP_SHIM = """#!/bin/sh
set -eu

stage="$HOME/.moonphase-clipboard/image.png"
want_targets=0
want_png=0
prev=""
for arg in "$@"; do
  case "$prev $arg" in
    "-t TARGETS") want_targets=1 ;;
    "-t image/png") want_png=1 ;;
  esac
  prev=$arg
done

[ -f "$stage" ] || exit 1

if [ "$want_targets" = 1 ]; then
  echo "image/png"
  exit 0
fi

if [ "$want_png" = 1 ]; then
  cat "$stage"
  rm -f "$stage"
  exit 0
fi

exit 1
"""


def _recipe(base_image: str, setup_script: str | None) -> str:
    """The full Dockerfile for an environment.

    Deliberately fails loudly on a base without apt rather than limping along:
    a container missing tmux or socat looks like a broken terminal, and the
    cause would be several layers away from the symptom.
    """
    packages = " ".join(BASE_PACKAGES)
    extra = (setup_script or "").strip()
    tmux_conf_b64 = base64.b64encode(TMUX_CONF.encode()).decode()
    xclip_shim_b64 = base64.b64encode(XCLIP_SHIM.encode()).decode()

    extra_step = ""
    if extra:
        # Base64 rather than folding the script into a single RUN. Joining
        # lines with `;` breaks multi-line shell constructs (`if ... then` is
        # not `if ...; then;`), and a heredoc would need a BuildKit syntax
        # directive. Encoding preserves the script exactly as written, quoting
        # and all.
        #
        # Runs as root, before dropping to `dev`, so package installs work.
        # This is the user's own server and their own definition; it is
        # ordinary provisioning, not a sandbox boundary.
        encoded = base64.b64encode(extra.encode()).decode()
        extra_step = f"""
# --- user-defined setup ---------------------------------------------------
USER root
RUN set -eux; \\
    echo {encoded} | base64 -d > /tmp/moonphase-setup.sh; \\
    sh -eux /tmp/moonphase-setup.sh; \\
    rm -f /tmp/moonphase-setup.sh
"""

    return f"""# Generated by Moonphase (recipe v{RECIPE_VERSION}). Do not edit by hand.
FROM {base_image}

ARG DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/sh", "-c"]

# Moonphase needs apt to install tmux, socat and iproute2. Without them a
# container starts but has no session, no port detection and no previews, so
# fail here where the reason is obvious.
RUN if ! command -v apt-get >/dev/null 2>&1; then \\
      echo "ERROR: Moonphase environments need a Debian or Ubuntu family base image."; \\
      echo "       '{base_image}' has no apt-get."; \\
      exit 1; \\
    fi

RUN apt-get update && apt-get install -y --no-install-recommends {packages} \\
    && (sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen 2>/dev/null || true) \\
    && (locale-gen 2>/dev/null || true) \\
    && rm -rf /var/lib/apt/lists/*

RUN ln -sf "$(command -v fdfind)" /usr/local/bin/fd || true

# Node from the official tarball, so the version does not depend on what the
# base image's distribution happens to package.
RUN set -eux; \\
    if ! command -v node >/dev/null 2>&1 || \\
       [ "$(node --version | cut -c2- | cut -d. -f1)" -lt 20 ]; then \\
      arch="$(dpkg --print-architecture)"; \\
      case "$arch" in \\
        amd64) node_arch='x64' ;; \\
        arm64) node_arch='arm64' ;; \\
        *) echo "unsupported architecture: $arch" >&2; exit 1 ;; \\
      esac; \\
      curl -fsSL "https://nodejs.org/dist/v{NODE_VERSION}/node-v{NODE_VERSION}-linux-${{node_arch}}.tar.xz" \\
        -o /tmp/node.tar.xz; \\
      tar -xJf /tmp/node.tar.xz -C /usr/local --strip-components=1 --no-same-owner; \\
      rm /tmp/node.tar.xz; \\
    fi; \\
    node --version; npm --version

ENV LANG=en_US.UTF-8 \\
    LC_ALL=en_US.UTF-8 \\
    TERM=xterm-256color

# GitHub CLI, so the agent can use the same token git does.
RUN mkdir -p -m 755 /etc/apt/keyrings \\
    && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \\
         -o /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \\
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \\
         > /etc/apt/sources.list.d/github-cli.list \\
    && apt-get update && apt-get install -y --no-install-recommends gh \\
    && rm -rf /var/lib/apt/lists/*

# Every harness Moonphase can run, in one image.
#
# One image rather than one per agent: a project can change harness without
# rebuilding, two sessions in the same container can run different agents, and
# the tag stays a function of the recipe rather than of what a project happens
# to be set to today. The cost is disk on the server, which is the cheap side of
# that trade.
RUN npm install -g @anthropic-ai/claude-code@latest opencode-ai@latest \
    && npm cache clean --force

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR=/usr/local/bin sh

# The Pydantic AI coder agent.
#
# `clai` is the executable; `pydantic-ai-harness` is the library holding the
# agent it runs. Installing the latter as a tool gets "No executables are
# provided by package", because it provides none — so the tool is clai, with the
# harness beside it, which is what `uvx --with` does in the documented one-liner.
#
# Both uv directories are set, and both matter. UV_TOOL_BIN_DIR places the
# shim; UV_TOOL_DIR places the virtualenv it points into. Setting only the first
# puts `clai` on PATH and leaves its environment under /root, so the session —
# which runs as `dev` — finds the command and cannot execute it: "Permission
# denied", from a binary that is plainly right there.
RUN env UV_TOOL_BIN_DIR=/usr/local/bin UV_TOOL_DIR=/opt/uv-tools \
    uv tool install clai --with "pydantic-ai-harness[anthropic,openai]" \
    && chmod -R a+rX /opt/uv-tools \
    && clai --version
{extra_step}
# Non-root by default, at a fixed uid so the API can chown the named volumes.
# Some bases ship their own uid 1000 user; 1001 avoids collisions either way.
USER root
RUN (userdel -r ubuntu 2>/dev/null || true); \\
    (id -u dev >/dev/null 2>&1 || useradd --create-home --shell /bin/bash --uid 1001 dev); \\
    echo 'dev ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/dev; \\
    chmod 0440 /etc/sudoers.d/dev; \\
    mkdir -p /workspace /home/dev/.claude /home/dev/.moonphase; \\
    chown -R dev:dev /workspace /home/dev

RUN set -eux; \\
    echo {tmux_conf_b64} | base64 -d > /home/dev/.tmux.conf; \\
    chown dev:dev /home/dev/.tmux.conf

# Lets the harness's own clipboard-image paste work with no X server and no
# real OS clipboard in the container.
RUN set -eux; \\
    echo {xclip_shim_b64} | base64 -d > /usr/local/bin/xclip; \\
    chmod +x /usr/local/bin/xclip

USER dev
WORKDIR /workspace

ENV npm_config_prefix=/home/dev/.npm-global
ENV PATH=/home/dev/.npm-global/bin:/home/dev/.local/bin:$PATH

ENTRYPOINT ["/usr/bin/tini", "-g", "--"]
CMD ["sleep", "infinity"]
"""



def recipe_for(base_image: str, setup_script: str | None) -> str:
    return _recipe(base_image, setup_script)


def image_tag(key: str, base_image: str, setup_script: str | None) -> str:
    """A tag derived from the recipe, so a changed definition is a new image.

    Reusing one tag across edits would leave projects silently running the old
    build, with no way to tell from the outside which one they got.
    """
    digest = hashlib.sha256(
        "\n".join([RECIPE_VERSION, base_image, setup_script or ""]).encode()
    ).hexdigest()[:12]
    safe_key = "".join(c if c.isalnum() or c in "-_" else "-" for c in key.lower())[:40]
    return f"moonphase/env-{safe_key or 'custom'}:{digest}"


async def image_exists(conn: asyncssh.SSHClientConnection, tag: str) -> bool:
    result = await ssh.run(
        conn, f"docker image inspect {shlex.quote(tag)} --format '{{{{.Id}}}}'", timeout=60
    )
    return result.ok


async def build_image(
    conn: asyncssh.SSHClientConnection,
    *,
    tag: str,
    base_image: str,
    setup_script: str | None,
    timeout: float = 2400.0,
) -> None:
    """Build the environment image on the server, from stdin, with no context."""
    dockerfile = _recipe(base_image, setup_script)
    log.info("building %s from %s", tag, base_image)

    result = await ssh.run(
        conn,
        f"docker build --pull -t {shlex.quote(tag)} -",
        timeout=timeout,
        stdin=dockerfile,
    )
    if not result.ok:
        # Docker puts build errors on stdout, so include both and keep the tail,
        # which is where the failing step actually is.
        combined = (result.stdout + "\n" + result.stderr).strip()
        raise SSHError(
            f"Could not build the environment image from {base_image}:\n"
            + combined[-1200:]
        )


async def ensure_image(
    conn: asyncssh.SSHClientConnection,
    *,
    tag: str,
    base_image: str,
    setup_script: str | None,
) -> bool:
    """Build the image if the server does not already have it. True if built."""
    if await image_exists(conn, tag):
        return False
    await build_image(
        conn, tag=tag, base_image=base_image, setup_script=setup_script
    )
    return True
