"""tmux session lifecycle inside a project container.

The whole premise of Moonphase rests on this file: the harness is owned by a
detached tmux server inside the container, not by any client connection. Every
attach is `tmux attach` over a fresh PTY, so dropping a WebSocket, closing a
laptop, or losing a train tunnel is indistinguishable from detaching — the
agent keeps working.
"""

from __future__ import annotations

import logging
import re
import shlex
from typing import Any

import asyncssh

from . import docker_remote, profile, ssh
from . import harness as harness_registry
from .harness import Harness, HarnessCredential
from .ssh import SSHError

log = logging.getLogger(__name__)

DEFAULT_SESSION = "moonphase"

# tmux treats '.' and ':' as target separators, so a session called "a.b" is
# unaddressable. Restricting the character set keeps every later `-t <name>`
# unambiguous rather than trying to escape at each call site.
_NAME_SAFE = re.compile(r"[^a-zA-Z0-9_-]+")


MOONPHASE_DIR = "/home/dev/.moonphase"
ENV_FILE = f"{MOONPHASE_DIR}/env"


def sanitise_name(name: str) -> str:
    """Coerce a user-supplied session name into something tmux can target."""
    cleaned = _NAME_SAFE.sub("-", (name or "").strip()).strip("-")[:48]
    return cleaned or DEFAULT_SESSION


def launcher_path(session: str) -> str:
    return f"{MOONPHASE_DIR}/launch-{session}.sh"


def _launcher_script(spec_command: list[str]) -> str:
    """Wrapper tmux actually owns.

    Sourcing the env file at launch (rather than baking credentials into
    `docker run -e`) means adding or rotating a key does not require recreating
    the container. Falling through to a shell keeps the pane — and therefore
    the tmux session — alive when the harness exits, so a crash does not
    destroy the window the user is about to reattach to.

    `set -m` is load-bearing. Without job control a non-interactive shell does
    not put its child in a new process group, so the harness and this wrapper
    share the terminal's foreground group: Ctrl-C then reaches the wrapper too,
    kills it, closes the pane, and destroys the tmux session the user was
    relying on surviving. With it, the harness owns its own process group and
    takes terminal signals alone.
    """
    argv = " ".join(shlex.quote(a) for a in spec_command)
    return f"""#!/bin/bash
# Generated by Moonphase. Edits will be overwritten.
set -a
[ -f {ENV_FILE} ] && . {ENV_FILE}
set +a

set -m

{argv}
status=$?

printf '\\n[moonphase] harness exited with status %s.\\n' "$status"
printf '[moonphase] press enter for a shell, or reattach later to restart.\\n'
read -r _
exec bash -l
"""


async def _write_file(
    conn: asyncssh.SSHClientConnection,
    container: str,
    path: str,
    contents: str,
    *,
    mode: str = "600",
) -> None:
    """Write a file inside the container without it ever hitting the host disk.

    The content goes over stdin of a `docker exec` running `cat`, so it is not
    visible in the process list on the managed server the way `echo secret`
    would be.
    """
    directory = shlex.quote(path.rsplit("/", 1)[0])
    quoted = shlex.quote(path)
    command = (
        f"docker exec -i -u dev {shlex.quote(container)} sh -c "
        + shlex.quote(
            f"mkdir -p {directory} && cat > {quoted} && chmod {mode} {quoted}"
        )
    )
    result = await ssh.run(conn, command, timeout=60, stdin=contents)
    result.check(f"Writing {path} into {container}")


async def apply_credential(
    conn: asyncssh.SSHClientConnection,
    container: str,
    harness: Harness,
    credential: HarnessCredential | None,
) -> None:
    """Materialise a bare harness credential, with no surrounding profile.

    Kept for tests and for the per-project override path. Normal session
    startup goes through `moonphase.profile.apply`, which also writes global
    settings and git configuration.
    """
    if credential is None:
        return

    for path, contents in harness.credential_files(credential).items():
        await _write_file(conn, container, path, contents)

    env = harness.credential_env(credential)
    if env:
        body = "".join(f"{k}={shlex.quote(v)}\n" for k, v in env.items())
        await _write_file(conn, container, ENV_FILE, body)


async def seed_config(
    conn: asyncssh.SSHClientConnection, container: str, harness: Harness
) -> None:
    """Write first-run config, but never over a file the harness already owns.

    Claude Code treats ~/.claude.json as its own mutable state (trust
    decisions, history, project settings). Overwriting it on every session
    start would silently discard all of that, so this is create-if-absent only.
    """
    for path, contents in harness.seed_config_files().items():
        quoted = shlex.quote(path)
        directory = shlex.quote(path.rsplit("/", 1)[0])
        command = (
            f"docker exec -i -u dev {shlex.quote(container)} sh -c "
            + shlex.quote(
                f"mkdir -p {directory}; "
                f"if [ ! -e {quoted} ]; then cat > {quoted} && chmod 600 {quoted}; "
                f"else cat > /dev/null; fi"
            )
        )
        await ssh.run(conn, command, timeout=60, stdin=contents)


async def is_authenticated(
    conn: asyncssh.SSHClientConnection, container: str, harness: Harness
) -> bool:
    """Whether the harness would find credentials if it started right now.

    `set -a` around the source mirrors what the launcher does, so the probe
    sees exactly the environment the harness will.
    """
    script = (
        f"set -a; [ -f {ENV_FILE} ] && . {ENV_FILE}; set +a; "
        f"{harness.auth_probe_script()}"
    )
    result = await docker_remote.exec_capture(
        conn, container, ["sh", "-c", script], timeout=30
    )
    return result.ok


async def session_exists(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> bool:
    result = await docker_remote.exec_capture(
        conn, container, ["tmux", "has-session", "-t", session], timeout=30
    )
    return result.ok


async def ensure_session(
    conn: asyncssh.SSHClientConnection,
    container: str,
    *,
    harness_kind: str,
    credential: HarnessCredential | None = None,
    workspace_profile: Any | None = None,
    session: str = DEFAULT_SESSION,
    restart: bool = False,
) -> bool:
    """Guarantee a detached tmux session running the harness. Returns True if created.

    Idempotent by design: the UI calls this on every project open, and an
    already-running session must be left strictly alone — recreating it would
    throw away the conversation the user came back for.

    The global profile is applied whenever one is supplied, so a container
    created before the user changed a setting picks the change up on its next
    restart without being re-provisioned.
    """
    harness = harness_registry.get(harness_kind)

    if restart and await session_exists(conn, container, session):
        await kill_session(conn, container, session)

    if await session_exists(conn, container, session):
        return False

    await seed_config(conn, container, harness)
    if workspace_profile is not None:
        await profile.apply(conn, container, harness, workspace_profile)
    else:
        await apply_credential(conn, container, harness, credential)

    spec = harness.launch_spec()
    await _write_file(
        conn, container, launcher_path(session), _launcher_script(spec.command), mode="700"
    )

    args = [
        "tmux",
        "new-session",
        "-d",
        "-s", session,
        "-c", spec.workdir,
        # A generous initial geometry; the first attach resizes to the real
        # client anyway, but starting at 80x24 makes the TUI reflow badly.
        "-x", "200",
        "-y", "50",
        launcher_path(session),
    ]
    result = await docker_remote.exec_capture(
        conn, container, args, workdir=spec.workdir, timeout=60
    )
    if not result.ok:
        raise SSHError(
            f"Could not start tmux session {session!r}: "
            f"{(result.stderr or result.stdout).strip()[:400]}"
        )

    # Keep scrollback deep enough that reattaching after hours still shows
    # context, and let tmux clean up only when we say so.
    await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "set-option", "-t", session, "history-limit", "50000"],
        timeout=30,
    )
    await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "set-option", "-t", session, "destroy-unattached", "off"],
        timeout=30,
    )
    log.info("started tmux session %s in %s", session, container)
    return True


async def kill_session(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> None:
    await docker_remote.exec_capture(
        conn, container, ["tmux", "kill-session", "-t", session], timeout=30
    )


async def send_keys(
    conn: asyncssh.SSHClientConnection,
    container: str,
    keys: str,
    *,
    session: str = DEFAULT_SESSION,
    enter: bool = True,
) -> None:
    """Type into the session without attaching a PTY.

    This is how the phone client will answer a permission prompt: the same tmux
    session receives the keystroke, so the desktop terminal shows it happening
    live. `-l` sends the string literally so it cannot be misread as a tmux
    key name.
    """
    args = ["tmux", "send-keys", "-t", session, "-l", keys]
    result = await docker_remote.exec_capture(conn, container, args, timeout=30)
    result.check("Sending keys to tmux")
    if enter:
        await docker_remote.exec_capture(
            conn, container, ["tmux", "send-keys", "-t", session, "Enter"], timeout=30
        )


async def capture_pane(
    conn: asyncssh.SSHClientConnection,
    container: str,
    *,
    session: str = DEFAULT_SESSION,
    lines: int = 200,
) -> str:
    """Plain-text snapshot of the pane, for previews and debugging."""
    result = await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "capture-pane", "-p", "-t", session, "-S", f"-{lines}"],
        timeout=30,
    )
    return result.stdout if result.ok else ""


# Printed by the attach wrapper before tmux takes the screen, so the bridge
# learns which tmux client it owns. Consumed by the bridge, never displayed.
TTY_MARKER = "MOONPHASE_TTY="


def attach_command(container: str, session: str = DEFAULT_SESSION) -> str:
    """Shell command that attaches a client to the session over a PTY.

    `-A` creates the session if it vanished, so a race between a health check
    and an attach cannot leave the user staring at an error.

    The wrapper announces its tty first because `docker exec` does not kill the
    process it started when its client goes away: closing the SSH channel
    leaves `tmux attach` running inside the container forever. Those phantom
    clients accumulate on every disconnect, and since tmux sizes a window to
    the most recent client, a single visit from a phone would pin the desktop
    to 60 columns permanently. Knowing our own tty lets the bridge detach
    itself explicitly on the way out.
    """
    inner = (
        f'printf "{TTY_MARKER}%s\\n" "$(tty)"; '
        f"exec tmux new-session -A -s {shlex.quote(session)}"
    )
    return docker_remote.exec_tty_command(
        container, ["sh", "-c", inner], workdir="/workspace"
    )


async def detach_client(
    conn: asyncssh.SSHClientConnection, container: str, tty: str
) -> None:
    """Detach one tmux client by its tty. Best effort."""
    if not tty.startswith("/dev/"):
        return
    await docker_remote.exec_capture(
        conn, container, ["tmux", "detach-client", "-t", tty], timeout=30
    )


async def list_clients(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> list[str]:
    """The ttys currently attached to a session."""
    result = await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "list-clients", "-t", session, "-F", "#{client_tty}"],
        timeout=30,
    )
    return result.stdout.split() if result.ok else []


async def detach_all_clients(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> int:
    """Detach every client. The escape hatch for phantoms already accumulated.

    Detaching never touches the session itself, so this is safe to offer as a
    plain button: worst case, an attached device reconnects a second later.
    """
    ttys = await list_clients(conn, container, session)
    for tty in ttys:
        await detach_client(conn, container, tty)
    return len(ttys)
