"""tmux session lifecycle inside a project container.

The whole premise of Moonphase rests on this file: the harness is owned by a
detached tmux server inside the container, not by any client connection. Every
attach is `tmux attach` over a fresh PTY, so dropping a WebSocket, closing a
laptop, or losing a train tunnel is indistinguishable from detaching — the
agent keeps working.
"""

from __future__ import annotations

import base64
import logging
import re
import shlex
import uuid
from typing import Any

import asyncssh

from . import docker_remote, profile, ssh
from . import harness as harness_registry
from .harness import Harness, HarnessCredential, SessionSpace
from .ssh import SSHError

log = logging.getLogger(__name__)

DEFAULT_SESSION = "moonphase"

# tmux treats '.' and ':' as target separators, so a session called "a.b" is
# unaddressable. Restricting the character set keeps every later `-t <name>`
# unambiguous rather than trying to escape at each call site.
_NAME_SAFE = re.compile(r"[^a-zA-Z0-9_-]+")


MOONPHASE_DIR = "/home/dev/.moonphase"

# Every session's private state lives under here, one directory per session.
# It is a plain directory rather than a volume because it must be visible to
# the same container the shared checkout is in.
SESSIONS_ROOT = "/home/dev/sessions"


def space_for(session: str, workdir: str | None = None) -> SessionSpace:
    """Where this session keeps its home and does its work."""
    from . import workspaces

    return SessionSpace(
        home=f"{SESSIONS_ROOT}/{session}",
        workdir=workdir or workspaces.workdir_for(session),
    )


def sanitise_name(name: str) -> str:
    """Coerce a user-supplied session name into something tmux can target."""
    cleaned = _NAME_SAFE.sub("-", (name or "").strip()).strip("-")[:48]
    return cleaned or DEFAULT_SESSION


def launcher_path(session: str) -> str:
    return f"{MOONPHASE_DIR}/launch-{session}.sh"


def _launcher_script(spec_command: list[str], space: SessionSpace) -> str:
    """Wrapper tmux actually owns.

    Sourcing the env file at launch (rather than baking credentials into
    `docker run -e`) means adding or rotating a key does not require recreating
    the container. Falling through to a shell keeps the pane — and therefore
    the tmux session — alive when the harness exits, so a crash does not
    destroy the window the user is about to reattach to.

    HOME is exported before anything else, because it is what keeps two people
    working in one container from sharing an account: the harness finds its
    credentials, its history and its transcripts relative to it, and so does
    git. The env file lives under that HOME and carries the rest.

    `set -m` is load-bearing. Without job control a non-interactive shell does
    not put its child in a new process group, so the harness and this wrapper
    share the terminal's foreground group: Ctrl-C then reaches the wrapper too,
    kills it, closes the pane, and destroys the tmux session the user was
    relying on surviving. With it, the harness owns its own process group and
    takes terminal signals alone.
    """
    argv = " ".join(shlex.quote(a) for a in spec_command)
    home = shlex.quote(space.home)
    env_file = shlex.quote(space.env_file)
    workdir = shlex.quote(space.workdir)
    return f"""#!/bin/bash
# Generated by Moonphase. Edits will be overwritten.
export HOME={home}
export GIT_CONFIG_GLOBAL={home}/.gitconfig

set -a
[ -f {env_file} ] && . {env_file}
set +a

cd {workdir} 2>/dev/null || cd /workspace

set -m

{argv}
status=$?

# Once the harness exits, this wrapper is the pane's foreground process again,
# and a stray Ctrl-C would kill it — closing the pane and destroying the
# session, which is exactly what `set -m` prevents while the harness is
# running. A no-op handler (rather than ignoring) survives only until the exec
# below, so the fallback shell still handles Ctrl-C normally.
trap : INT

printf '\\n[moonphase] harness exited with status %s.\\n' "$status"
printf '[moonphase] press enter for a shell, or reattach later to restart.\\n'
read -r _
exec bash -l
"""


async def _write_file(
    conn: asyncssh.SSHClientConnection,
    container: str,
    path: str,
    contents: str,
    *,
    mode: str = "600",
) -> None:
    """Write a file inside the container without it ever hitting the host disk.

    The content goes over stdin of a `docker exec` running `cat`, so it is not
    visible in the process list on the managed server the way `echo secret`
    would be.
    """
    directory = shlex.quote(path.rsplit("/", 1)[0])
    quoted = shlex.quote(path)
    command = (
        f"docker exec -i -u dev {shlex.quote(container)} sh -c "
        + shlex.quote(
            f"mkdir -p {directory} && cat > {quoted} && chmod {mode} {quoted}"
        )
    )
    result = await ssh.run(conn, command, timeout=60, stdin=contents)
    result.check(f"Writing {path} into {container}")


async def write_upload(
    conn: asyncssh.SSHClientConnection,
    container: str,
    path: str,
    data: bytes,
) -> None:
    """Write an uploaded file (an image from the feed) into the container.

    The SSH channel that carries `stdin` here is text, not bytes, so raw image
    data would corrupt in transit; base64 survives it, and `base64 -d` on the
    other end restores the original bytes.
    """
    directory = shlex.quote(path.rsplit("/", 1)[0])
    quoted = shlex.quote(path)
    command = (
        f"docker exec -i -u dev {shlex.quote(container)} sh -c "
        + shlex.quote(f"mkdir -p {directory} && base64 -d > {quoted} && chmod 644 {quoted}")
    )
    result = await ssh.run(conn, command, timeout=60, stdin=base64.b64encode(data).decode())
    result.check(f"Writing {path} into {container}")


async def ensure_home(
    conn: asyncssh.SSHClientConnection, container: str, space: SessionSpace
) -> None:
    """Create a session's home, seeded with the shell dotfiles.

    Copied rather than symlinked so a session can diverge, and only when
    absent so a restart does not undo whatever the user changed. Without this
    the fallback shell at the end of the launcher would start with no rc file
    at all, which reads as a broken terminal rather than a fresh one.
    """
    home = shlex.quote(space.home)
    script = (
        f"mkdir -p {home} && chmod 700 {home} && "
        f"for f in .bashrc .profile .bash_logout; do "
        f'  [ -e {home}/$f ] || cp /home/dev/$f {home}/$f 2>/dev/null || true; '
        f"done; true"
    )
    result = await docker_remote.exec_capture(
        conn, container, ["sh", "-c", script], timeout=60
    )
    if not result.ok:
        raise SSHError(
            f"Could not prepare the session home {space.home}: "
            f"{(result.stderr or result.stdout).strip()[:300]}"
        )


async def apply_credential(
    conn: asyncssh.SSHClientConnection,
    container: str,
    harness: Harness,
    credential: HarnessCredential | None,
    space: SessionSpace | None = None,
) -> None:
    """Materialise a bare harness credential, with no surrounding profile.

    Kept for tests and for the per-project override path. Normal session
    startup goes through `moonphase.profile.apply`, which also writes global
    settings and git configuration.
    """
    space = space or SessionSpace()
    if credential is None:
        return

    for path, contents in harness.credential_files(credential, space).items():
        await _write_file(conn, container, path, contents)

    env = dict(harness.credential_env(credential))
    env["HOME"] = space.home
    body = "".join(f"{k}={shlex.quote(v)}\n" for k, v in env.items())
    await _write_file(conn, container, space.env_file, body)


async def seed_config(
    conn: asyncssh.SSHClientConnection,
    container: str,
    harness: Harness,
    space: SessionSpace | None = None,
) -> None:
    """Write first-run config, but never over a file the harness already owns.

    Claude Code treats ~/.claude.json as its own mutable state (trust
    decisions, history, project settings). Overwriting it on every session
    start would silently discard all of that, so this is create-if-absent only.
    """
    space = space or SessionSpace()
    for path, contents in harness.seed_config_files(space).items():
        quoted = shlex.quote(path)
        directory = shlex.quote(path.rsplit("/", 1)[0])
        command = (
            f"docker exec -i -u dev {shlex.quote(container)} sh -c "
            + shlex.quote(
                f"mkdir -p {directory}; "
                f"if [ ! -e {quoted} ]; then cat > {quoted} && chmod 600 {quoted}; "
                f"else cat > /dev/null; fi"
            )
        )
        await ssh.run(conn, command, timeout=60, stdin=contents)


async def is_authenticated(
    conn: asyncssh.SSHClientConnection,
    container: str,
    harness: Harness,
    space: SessionSpace | None = None,
) -> bool:
    """Whether the harness would find credentials if it started right now.

    `set -a` around the source mirrors what the launcher does, so the probe
    sees exactly the environment the harness will.
    """
    space = space or SessionSpace()
    script = (
        f"set -a; [ -f {shlex.quote(space.env_file)} ] "
        f"&& . {shlex.quote(space.env_file)}; set +a; "
        f"{harness.auth_probe_script(space)}"
    )
    result = await docker_remote.exec_capture(
        conn, container, ["sh", "-c", script], timeout=30
    )
    return result.ok


async def session_exists(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> bool:
    result = await docker_remote.exec_capture(
        conn, container, ["tmux", "has-session", "-t", session], timeout=30
    )
    return result.ok


async def ensure_session(
    conn: asyncssh.SSHClientConnection,
    container: str,
    *,
    harness_kind: str,
    credential: HarnessCredential | None = None,
    workspace_profile: Any | None = None,
    session: str = DEFAULT_SESSION,
    space: SessionSpace | None = None,
    restart: bool = False,
    resume: bool = False,
) -> bool:
    """Guarantee a detached tmux session running the harness. Returns True if created.

    Idempotent by design: the UI calls this on every project open, and an
    already-running session must be left strictly alone — recreating it would
    throw away the conversation the user came back for.

    The global profile is applied whenever one is supplied, so a container
    created before the user changed a setting picks the change up on its next
    restart without being re-provisioned.
    """
    harness = harness_registry.get(harness_kind)
    # Defaults to the shared single-user layout, not to a derived per-session
    # one: the per-session workdir is a git worktree that something else has to
    # have created, and silently pointing tmux at a directory that does not
    # exist fails in a way that reads as "tmux is broken".
    space = space or SessionSpace()

    if restart and await session_exists(conn, container, session):
        await kill_session(conn, container, session)

    already = await session_exists(conn, container, session)

    # Configuration is written even when the session is already up. It cannot
    # reach the harness process that is running — environment is read once, at
    # launch — but it means a credential rotated in Settings is in place for
    # the next restart rather than silently absent until someone recreates the
    # session by hand.
    await ensure_home(conn, container, space)
    await seed_config(conn, container, harness, space)
    if workspace_profile is not None:
        await profile.apply(conn, container, harness, workspace_profile, space)
    else:
        await apply_credential(conn, container, harness, credential, space)

    # The credential can come from either branch above; the profile's is the
    # one a session actually runs on when there is a profile.
    launch_credential = (
        workspace_profile.harness_credential
        if workspace_profile is not None
        else credential
    )
    spec = harness.launch_spec(resume=resume, credential=launch_credential)
    await _write_file(
        conn,
        container,
        launcher_path(session),
        _launcher_script(spec.command, space),
        mode="700",
    )

    if already:
        return False

    args = [
        "tmux",
        "new-session",
        "-d",
        "-s", session,
        "-c", space.workdir,
        # Session-scoped so a pane the user opens by hand inside tmux lands in
        # the same home as the harness. Only non-secret values go here: tmux
        # arguments are visible in the container's process list, which is why
        # credentials stay in the env file instead.
        "-e", f"HOME={space.home}",
        "-e", f"GIT_CONFIG_GLOBAL={space.git_config}",
        # A generous initial geometry; the first attach resizes to the real
        # client anyway, but starting at 80x24 makes the TUI reflow badly.
        "-x", "200",
        "-y", "50",
        launcher_path(session),
    ]
    result = await docker_remote.exec_capture(
        conn, container, args, workdir=space.workdir, timeout=60
    )
    if not result.ok:
        raise SSHError(
            f"Could not start tmux session {session!r}: "
            f"{(result.stderr or result.stdout).strip()[:400]}"
        )

    # Keep scrollback deep enough that reattaching after hours still shows
    # context, and let tmux clean up only when we say so.
    await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "set-option", "-t", session, "history-limit", "50000"],
        timeout=30,
    )
    await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "set-option", "-t", session, "destroy-unattached", "off"],
        timeout=30,
    )
    log.info("started tmux session %s in %s", session, container)
    return True


async def kill_session(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> None:
    await docker_remote.exec_capture(
        conn, container, ["tmux", "kill-session", "-t", session], timeout=30
    )


async def send_keys(
    conn: asyncssh.SSHClientConnection,
    container: str,
    keys: str,
    *,
    session: str = DEFAULT_SESSION,
    enter: bool = True,
) -> None:
    """Type into the session without attaching a PTY.

    This is how the phone client will answer a permission prompt: the same tmux
    session receives the keystroke, so the desktop terminal shows it happening
    live. `-l` sends the string literally so it cannot be misread as a tmux
    key name.
    """
    args = ["tmux", "send-keys", "-t", session, "-l", keys]
    result = await docker_remote.exec_capture(conn, container, args, timeout=30)
    result.check("Sending keys to tmux")
    if enter:
        await docker_remote.exec_capture(
            conn, container, ["tmux", "send-keys", "-t", session, "Enter"], timeout=30
        )


async def capture_pane(
    conn: asyncssh.SSHClientConnection,
    container: str,
    *,
    session: str = DEFAULT_SESSION,
    lines: int = 200,
) -> str:
    """Plain-text snapshot of the pane, for previews and debugging."""
    result = await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "capture-pane", "-p", "-t", session, "-S", f"-{lines}"],
        timeout=30,
    )
    return result.stdout if result.ok else ""


# Printed by the attach wrapper before tmux takes the screen, so the bridge
# learns which tmux client it owns. Consumed by the bridge, never displayed.
TTY_MARKER = "MOONPHASE_TTY="


def attach_command(
    container: str,
    session: str = DEFAULT_SESSION,
    *,
    read_only: bool = False,
    workdir: str = "/workspace",
) -> str:
    """Shell command that attaches a client to the session over a PTY.

    `-A` creates the session if it vanished, so a race between a health check
    and an attach cannot leave the user staring at an error.

    The wrapper announces its tty first because `docker exec` does not kill the
    process it started when its client goes away: closing the SSH channel
    leaves `tmux attach` running inside the container forever. Those phantom
    clients accumulate on every disconnect, and since tmux sizes a window to
    the most recent client, a single visit from a phone would pin the desktop
    to 60 columns permanently. Knowing our own tty lets the bridge detach
    itself explicitly on the way out.

    `read_only` is for someone a project was shared with as a viewer. It adds
    `ignore-size` as well as `-r`: a viewer who cannot type could otherwise
    still squeeze the window for whoever is driving, which is the same defect
    as a phantom client and just as baffling to run into. It also attaches
    rather than creating — a viewer arriving at a project with nothing running
    should be told so, not silently start a session.
    """
    if read_only:
        attach = (
            f"exec tmux attach-session -r -f ignore-size -t {shlex.quote(session)}"
        )
    else:
        attach = f"exec tmux new-session -A -s {shlex.quote(session)}"
    inner = f'printf "{TTY_MARKER}%s\\n" "$(tty)"; {attach}'
    return docker_remote.exec_tty_command(
        container, ["sh", "-c", inner], workdir=workdir
    )


async def detach_client(
    conn: asyncssh.SSHClientConnection, container: str, tty: str
) -> None:
    """Detach one tmux client by its tty. Best effort."""
    if not tty.startswith("/dev/"):
        return
    await docker_remote.exec_capture(
        conn, container, ["tmux", "detach-client", "-t", tty], timeout=30
    )


async def list_clients(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> list[str]:
    """The ttys currently attached to a session."""
    result = await docker_remote.exec_capture(
        conn,
        container,
        ["tmux", "list-clients", "-t", session, "-F", "#{client_tty}"],
        timeout=30,
    )
    return result.stdout.split() if result.ok else []


async def capture_all_panes(
    conn: asyncssh.SSHClientConnection,
    container: str,
    *,
    lines: int = 80,
) -> dict[str, str]:
    """Every live session's pane, in one call.

    The monitor used to ask per session — list, then capture, then inspect the
    container again — so a project with four agents cost twelve round trips
    every sweep, eleven of them re-asking things it already knew. This asks
    once and comes back with the lot.

    Panes are separated by a marker carrying a nonce rather than a fixed
    string, because the thing being delimited is arbitrary terminal output and
    a fixed delimiter is one `echo` away from being forged by the very content
    it is supposed to bound.
    """
    nonce = uuid.uuid4().hex
    marker = f"@@MOONPHASE-{nonce}@@"
    script = (
        'names=$(tmux list-sessions -F "#{session_name}" 2>/dev/null); '
        'for name in $names; do '
        f'  printf "\n{marker}%s\n" "$name"; '
        f'  tmux capture-pane -p -t "$name" -S -{int(lines)} 2>/dev/null; '
        "done"
    )
    result = await docker_remote.exec_capture(
        conn, container, ["sh", "-c", script], timeout=45
    )
    if not result.ok:
        return {}

    panes: dict[str, str] = {}
    for chunk in result.stdout.split(marker)[1:]:
        name, _, body = chunk.partition("\n")
        panes[name.strip()] = body
    return panes


async def client_counts(
    conn: asyncssh.SSHClientConnection, container: str
) -> dict[str, int]:
    """Attached client counts for every session, in one call.

    With no `-t`, `list-clients` reports every client on the server, so this
    stays two execs whether a project has one session or ten.

    It used to pass `-a`, which `list-clients` does not accept — tmux answered
    "unknown flag" and the counts came back all zero. Nothing failed loudly:
    the UI simply never showed a device count, which also meant it never showed
    phantom clients piling up until the server ran out of channels.
    """
    live = await docker_remote.exec_capture(
        conn, container, ["tmux", "list-sessions", "-F", "#{session_name}"], timeout=30
    )
    if not live.ok:
        return {}

    counts = {name: 0 for name in live.stdout.split()}

    clients = await docker_remote.exec_capture(
        conn, container, ["tmux", "list-clients", "-F", "#{client_session}"],
        timeout=30,
    )
    if clients.ok:
        for name in clients.stdout.split():
            if name in counts:
                counts[name] += 1
    return counts


# ttys this process is currently bridging, per container. Anything attached to
# a session that is *not* in here belongs to a bridge that has gone — a crashed
# client, a killed backend, a dropped connection whose cleanup never ran.
_live_clients: dict[str, set[str]] = {}


def register_client(container: str, tty: str) -> None:
    _live_clients.setdefault(container, set()).add(tty)


def release_client(container: str, tty: str) -> None:
    _live_clients.get(container, set()).discard(tty)


async def reap_phantom_clients(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> int:
    """Detach clients of this session that no live bridge owns.

    `docker exec` does not kill the process it started when its client goes
    away, so every disconnect whose cleanup did not run leaves a `tmux attach`
    holding a client — and an SSH channel — forever. sshd allows ten channels
    by default, so about ten stale attaches take the project down: the terminal
    cannot open a channel, and neither can the command that would clean up.

    The bridge already detaches itself on the way out. This is the backstop for
    when it could not: it runs before each attach, and because the set of live
    ttys is process state, a restarted backend correctly considers every client
    it finds to be stale.
    """
    ours = _live_clients.get(container, set())
    detached = 0
    for tty in await list_clients(conn, container, session):
        if tty in ours:
            continue
        await detach_client(conn, container, tty)
        detached += 1
    if detached:
        log.info(
            "detached %d phantom client(s) from %s in %s", detached, session, container
        )
    return detached


async def detach_all_clients(
    conn: asyncssh.SSHClientConnection, container: str, session: str = DEFAULT_SESSION
) -> int:
    """Detach every client. The escape hatch for phantoms already accumulated.

    Detaching never touches the session itself, so this is safe to offer as a
    plain button: worst case, an attached device reconnects a second later.
    """
    ttys = await list_clients(conn, container, session)
    for tty in ttys:
        await detach_client(conn, container, tty)
    return len(ttys)
