#!/usr/bin/env python3
"""Generate a VAPID keypair for web push.

Web push needs an application server keypair. It is per-deployment and has no
third party involved: the browser vendor's endpoint verifies the signature
against the public key the client subscribed with.

    apps/api/.venv/bin/python scripts/gen_vapid.py >> .env

Regenerating invalidates every existing subscription — browsers will simply
stop accepting pushes signed by the new key, and users re-enable notifications.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "apps" / "api"))

from moonphase import push  # noqa: E402


def main() -> None:
    public, private_pem = push.generate_keypair()

    # The private key is multi-line PEM, which .env cannot hold unquoted.
    one_line = private_pem.replace("\n", "\\n")

    print("# --- web push (generated by scripts/gen_vapid.py) ---")
    print(f"MOONPHASE_VAPID_PUBLIC_KEY={public}")
    print(f'MOONPHASE_VAPID_PRIVATE_KEY="{one_line}"')
    print("MOONPHASE_VAPID_SUBJECT=mailto:you@example.com")


if __name__ == "__main__":
    main()
